### ISSUE TITLE
Breaks ACF Time Picker Field

### ISSUE THREAD

**Issue by ViSi19** [WPChill/check-email#11]
https://wordpress.org/support/topic/breaks-acf-time-picker-field/ 
Da, in momentul in care faci un nou field de exemplu cu aceste setari https://gyazo.com/a3aa2d7a585ff1d42d3e26bee5b8e991 si selectezi in pagina iti apare calendarul https://gyazo.com/0bae8db6e5cbc92bf9f472c7e52f9b0e

**Comment by TeoAlex** [comment]
Tested Time Picker, Date Picker, DateTime Picker. All working.
