### ISSUE TITLE
Check email suprapune CSS pe pagina de editatare Divi.

### ISSUE THREAD

**Issue by ViSi19** [WPChill/check-email#13]
https://drive.google.com/file/d/1KXgYdIVz7Gy3lI7ty2oa9M9KzaD_6g3n/view?usp=sharing -> Aici aveti o theme Divi. 
Cand este activat check email se incarca si pe pagina acestuia CSS-ul. https://gyazo.com/dd73b6d7f7756eac6b36a3833a21ed06 
Un video mai bine indetaliat al probmelei este aici: https://recordit.co/thjPzTzSZB

**Comment by andyluak** [comment]
Works
