### ISSUE TITLE
 Deprecated jQuery functions

### ISSUE THREAD

**Issue by mplusb** [WPChill/check-email#14]
https://wordpress.org/support/topic/deprecated-jquery-functions/

WordPress 5.6 and Check & Log email Version 1.0.1

/plugins/check-email/assets/vendor/jquery-ui/jquery-ui.min.js

jQuery.expr[\’:\’] is deprecated; use jQuery.expr.pseudos
jQuery.isFunction() is deprecated
jQuery.isArray is deprecated; use Array.isArray
jQuery.expr.filters is deprecated; use jQuery.expr.pseudos

**Comment by andyluak** [comment]
No errors thrown
