### ISSUE TITLE
use unique prefixes for the functions

### ISSUE THREAD

**Issue by mplusb** [WPChill/check-email#16]
use unique prefixes for the functions 😉

Fatal error: Cannot redeclare check_email() (previously declared in /srv/users/user/apps/app/public/wp-content/themes/theme/include/misc_func.php:96) in /srv/users/user/apps/fwsnl/public/wp-content/plugins/check-email/check-email.php on line app

https://wordpress.org/support/topic/wrong-info-for-current-mail-settings/

**Comment by andyluak** [comment]
check_email function has been prefixed
