### ISSUE TITLE
wrong info

### ISSUE THREAD

**Issue by mplusb** [WPChill/check-email#18]
I’m sending e-mails using the sendgrid (the old native) plugin and the information is still showing this:

SendMail path (UNIX): /usr/sbin/sendmail -t -i
SMTP server (Windows): localhost
SMTP port (Windows): 25
Add X header: 0

This information is wrong, while all emails are still logged.

I’m using the API option from this plugin:
https://wordpress.org/plugins/sendgrid-email-delivery-simplified/

On other sites I use the Postmark API with this official plugin:
https://wordpress.org/plugins/postmark-approved-wordpress-plugin/

Both times I get the “wrong” information.
https://wordpress.org/support/topic/wrong-info-for-current-mail-settings/

**Comment by andyluak** [comment]
The dev branch had a commit regarding this matter and now it logs correctly
