### ISSUE TITLE
the widget is broken

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/check-email#33]
The widget seems to be broken, it renders some HTML, namely:

Total number of emails logged: 0

<a href="admin.php?page=check-email-status">Status</a> | <a href="admin.php?page=check-email-logs">Email Logs</a> | <a href="admin.php?page=check-email-settings">Settings</a> |
The issue appears even on clean install of WP.

https://wordpress.org/support/topic/something-is-wrong-with-the-widget/

**Comment by cristianraiber** [comment]
Works now: 

![image](https://user-images.githubusercontent.com/7841556/154228160-66607143-124b-4d06-a434-54c60878c552.png)
