### ISSUE TITLE
Add tabs and group settings by tabs

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/check-email#37]
![image](https://user-images.githubusercontent.com/7841556/154229751-ad0c79fd-6fba-433c-b85c-efa0971314b5.png)

**Comment by cristianraiber** [comment]
Setting grouping:

General
- Allowed user Roles
- Enable Dashboard Widget
- Remove data on uninstall
- Override emails from section

Logging:
- Enable Email Logging (change label from 'Enable logs')
- Database Size notification

**Comment by razvanaldea89** [comment]
@TeoAlex current 1 click install should be replaced with - https://github.com/WPChill/download-monitor/blob/master/assets/js/install-plugins.js
