### ISSUE TITLE
Version 1.0 broke site email, perhaps conflict with other plugins

### ISSUE THREAD

**Issue by cristinnaiulia** [WPChill/check-email#8]
I have auto-updates enabled for plugins, and a few days ago the last email sent from my site was a notification that Check & Log Email was not up to date. (Version 1.0).

Since then, my site could not send any emails – order confirmation, contact form, etc. Disable Check & Log Email plugin, all works again.

Had been working perfectly, but Version 1.0 may have conflict with other email plugins I have installed: WP Mail SMTP and WP Mail Log.

**Comment by andyluak** [comment]
Works
